
all: rvalue filter reverse

rvalue:
	g++ -g -Wall -pedantic -std=c++11 rvalue.cpp -o rvalue
	./rvalue

filter:
	g++ -g -Wall -pedantic -std=c++11 filter.cpp -o filter
	./filter

reverse:
	g++ -g -Wall -pedantic -std=c++11 reverse.cpp -o reverse
	./reverse
